Repository SceneGate/Yarhl, pull requests merged in 2019-10, with the labels that each got.

#117 Unify NuGet versions and update code analyzers
  build.cake
  src/Common.props
  src/Directory.Build.props
  src/SceneGate.Standard.ruleset
  src/SceneGate.Test.ruleset
  src/StyleCop.ruleset
  src/StyleCopTests.ruleset
  src/Yarhl.IntegrationTests/Yarhl.IntegrationTests.csproj
  src/Yarhl.Media/Yarhl.Media.csproj
  src/Yarhl.PerformanceTests/Yarhl.PerformanceTests.csproj
  src/Yarhl.UnitTests/Yarhl.UnitTests.csproj
  src/Yarhl/PluginManager.cs
  src/Yarhl/Yarhl.csproj
Labels: enhancement

#118 New API for keeping the dispose ownership of Streams
  README.md
  src/Yarhl.IntegrationTests/PluginDiscovery.cs
  src/Yarhl.UnitTests/IO/BinaryFormatTests.cs
  src/Yarhl.UnitTests/IO/DataReaderTests.cs
  src/Yarhl.UnitTests/IO/DataStreamFactoryTests.cs
  src/Yarhl.UnitTests/IO/DataStreamTests.cs
  src/Yarhl.UnitTests/IO/DataWriterTests.cs
  src/Yarhl/FileFormat/ConvertFormat.cs
  src/Yarhl/FileSystem/NodeFactory.cs
  src/Yarhl/IO/DataStream.cs
  src/Yarhl/IO/DataStreamFactory.cs
  src/Yarhl/IO/IBinary.cs
Labels: core, enhancement

#119 Do not dispose when changing to the same format instance
  src/Yarhl.UnitTests/FileSystem/NodeTests.cs
  src/Yarhl/FileSystem/Node.cs
Labels: enhancement

#120 Split the PO converter into two classes
  src/Yarhl.Media/Text/Binary2Po.cs
  src/Yarhl.Media/Text/Po2Binary.cs
  src/Yarhl.UnitTests/Media/Text/Po2BinaryTests.cs
Labels: breaking, enhancement

#122 Fix warnings from new code analyzers
  build.cake
  src/Directory.Build.props
  src/SceneGate.Test.ruleset
  src/Yarhl.Media/Text/Encodings/EscapeOutRangeEncoding.cs
  src/Yarhl.Media/Text/Encodings/EucJpEncoding.cs
  src/Yarhl.UnitTests/FileFormat/ConvertFormatTests.cs
  src/Yarhl.UnitTests/FileFormat/ConverterMetadataTests.cs
  src/Yarhl.UnitTests/FileFormat/Converters.cs
  src/Yarhl.UnitTests/FileSystem/NavigableNodeTests.cs
  src/Yarhl.UnitTests/FileSystem/NavigatorTests.cs
  src/Yarhl.UnitTests/FileSystem/NodeContainerFormatTests.cs
  src/Yarhl.UnitTests/FileSystem/NodeFactoryTests.cs
  src/Yarhl.UnitTests/FileSystem/NodeTests.cs
  src/Yarhl.UnitTests/IO/BinaryFormatTests.cs
  src/Yarhl.UnitTests/IO/DataStreamFactoryTests.cs
  src/Yarhl.UnitTests/IO/DataStreamTests.cs
  src/Yarhl.UnitTests/IO/DataWriterTests.cs
  src/Yarhl.UnitTests/IO/StreamFormat/LazyFileStreamTests.cs
  src/Yarhl.UnitTests/IO/StreamFormat/RecyclableMemoryStreamTests.cs
  src/Yarhl.UnitTests/IO/StreamFormat/StreamWrapperTests.cs
  src/Yarhl.UnitTests/IO/TextWriterTests.cs
  src/Yarhl.UnitTests/Media/Text/Encodings/EscapeOutRangeEncodingTests.cs
  src/Yarhl.UnitTests/Media/Text/Po2BinaryTests.cs
  src/Yarhl.UnitTests/PluginManagerTests.cs
  src/Yarhl.UnitTests/Yarhl.UnitTests.csproj
  src/Yarhl/AssemblyUtils.cs
  src/Yarhl/FileSystem/NavigableNode.cs
  src/Yarhl/FileSystem/Navigator.cs
  src/Yarhl/Gendarme.ignore
  src/Yarhl/PluginManager.cs
Labels: enhancement

#108 Cookbook
  docs/articles/Cookbook.md
  docs/articles/toc.yml
Labels: doc
