Repository SceneGate/Yarhl, pull requests merged in 2019-08, with the labels that each got.

#103 Check the return code from the converters when transforming the format of a node
  azure-pipelines.yml
  build.cake
  src/Yarhl.UnitTests/FileFormat/Converters.cs
  src/Yarhl.UnitTests/FileSystem/NodeTests.cs
  src/Yarhl/FileSystem/Node.cs
  tools/packages.config
Labels: enhancement

#106 Added API version to the docs website
  fusion/toc.html
  index.html
  toc.html
Labels: doc

#107 Updated README doc link and added docs version
  README.md
  docs/fusion/toc.yml
  docs/toc.yml
Labels: doc

#109 Add extensibility to streams
  src/Common.props
  src/Yarhl.UnitTests/IO/DataReaderTests.cs
  src/Yarhl.UnitTests/IO/DataStreamTests.cs
  src/Yarhl.UnitTests/IO/DataWriterTests.cs
  src/Yarhl/Gendarme.ignore
  src/Yarhl/IO/DataReader.cs
  src/Yarhl/IO/DataStream.cs
  src/Yarhl/IO/DataWriter.cs
  src/Yarhl/IO/IStream.cs
  src/Yarhl/IO/TextReader.cs
  src/Yarhl/IO/TextWriter.cs
Labels: breaking, core

#111 Improve DataStreams extensibility and add lazy FileStream and recyclable MemoryStream
  build.cake
  src/Yarhl.UnitTests/FileSystem/NodeFactoryTests.cs
  src/Yarhl.UnitTests/IO/BinaryFormatTests.cs
  src/Yarhl.UnitTests/IO/DataStreamFactoryTests.cs
  src/Yarhl.UnitTests/IO/DataStreamTests.cs
  src/Yarhl.UnitTests/IO/StreamFormat/LazyFileStreamTests.cs
  src/Yarhl.UnitTests/IO/StreamFormat/RecyclableMemoryStreamTests.cs
  src/Yarhl.UnitTests/IO/StreamFormat/StreamWrapperTests.cs
  src/Yarhl/FileSystem/NodeFactory.cs
  src/Yarhl/Gendarme.ignore
  src/Yarhl/IO/BinaryFormat.cs
  src/Yarhl/IO/DataReader.cs
  src/Yarhl/IO/DataStream.cs
  src/Yarhl/IO/DataStreamFactory.cs
  src/Yarhl/IO/DataWriter.cs
  src/Yarhl/IO/IStream.cs
  src/Yarhl/IO/StreamFormat/LazyFileStream.cs
  src/Yarhl/IO/StreamFormat/RecyclableMemoryStream.cs
  src/Yarhl/IO/StreamFormat/StreamWrapper.cs
  src/Yarhl/IO/TextReader.cs
  src/Yarhl/IO/TextWriter.cs
  src/Yarhl/Yarhl.csproj
Labels: breaking, core
