Repository SceneGate/Yarhl, pull requests merged in 2020-10, with the labels that each got.

#145 Add missing types
  src/Yarhl.UnitTests/IO/DataReaderTests.cs
  src/Yarhl.UnitTests/IO/DataWriterTests.cs
  src/Yarhl/IO/DataReader.cs
  src/Yarhl/IO/DataWriter.cs
Labels: IO, enhancement, hacktoberfest-accepted

#144 Implemented Stream.WriteTo with custom offset
  src/Yarhl.UnitTests/FileFormat/ConvertFormatTests.cs
  src/Yarhl.UnitTests/IO/DataStreamTests.cs
  src/Yarhl/IO/DataStream.cs
Labels: IO, enhancement, hacktoberfest-accepted

#147 Solved DataStream.WriteTo does not create the file when the length is…
  src/Yarhl.UnitTests/IO/DataStreamTests.cs
  src/Yarhl/IO/DataStream.cs
Labels: IO, bug, hacktoberfest-accepted

#146 Remove double slashes in path
  src/Yarhl.UnitTests/FileSystem/NodeFactoryTests.cs
  src/Yarhl/FileSystem/NodeFactory.cs
Labels: bug, core, hacktoberfest-accepted

#148 Solved DataStreamFactory does not check if the file exists when openi…
  src/Yarhl.UnitTests/IO/DataStreamFactoryTests.cs
  src/Yarhl/IO/DataStreamFactory.cs
Labels: IO, core, enhancement, hacktoberfest-accepted

#149 Custom string terminators
  src/Yarhl.UnitTests/IO/DataWriterTests.cs
  src/Yarhl/IO/DataWriter.cs
Labels: IO, enhancement, hacktoberfest-accepted
